MyFreends/urls.py
from allauth.account.views import login
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth.views import LogoutView
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('friendship.urls')),
    path('', include('user.urls')),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('', include('allauth.urls')),
    path('', login, name='login'),
    path('', include('chat.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
else:
    urlpatterns += staticfiles_urlpatterns()

chat/urls.py
from django.urls import path
from chat.views import chat, upload_image

urlpatterns = [
    path('chat/', chat, name='chat'),
    path('chat/up_image/', upload_image, name='upload'),
]

user/urls.py
from allauth.account.decorators import verified_email_required
from django.urls import path

from user.views import UserDetailView, UpdateImage

urlpatterns = [
    path(
        'my_profile/', verified_email_required(UserDetailView.as_view()),
        name='my_profile'
    ),
    path(
        'update_image/', verified_email_required(UpdateImage.as_view()),
        name='update_image'
    )
]

user/models.py
from django.contrib.auth.models import User, AbstractBaseUser, PermissionsMixin
from django.db import models
from django.urls import reverse, reverse_lazy
from django.utils.crypto import get_random_string

from user.managers import CustomStaffManager


def user_image(instance, filename):
    return '%s/image/%s' % (instance.url, filename)


class User(AbstractBaseUser, PermissionsMixin):
    url = models.SlugField('url', max_length=20, unique=True)
    email = models.EmailField(
        'Адрес электронной почты', max_length=254, unique=True
    )
    first_name = models.CharField('Имя', max_length=50)
    last_name = models.CharField('Фамилия', max_length=50)
    birthday = models.DateField('Дата рождения')
    image = models.ImageField(
        'Фото', upload_to=user_image, default='default.png'
    )
    objects = CustomStaffManager()
    is_staff = models.BooleanField('Персонал', default=False)
    is_superuser = models.BooleanField('Админ', default=False)
    is_close = models.BooleanField('Закрытый', default=False)
    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ('first_name', 'last_name', 'url', 'birthday')

    def save(self, *args, **kwargs):
        if self.url == '':
            self.url = get_random_string(6)
        super(User, self).save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('user', kwargs=(self.url))

    class Meta:
        verbose_name = 'Учетная запись'
        verbose_name_plural = 'Учетные записи'

user/forms.py
from PIL import Image
from allauth.account import app_settings
from allauth.account.forms import LoginForm
from allauth.utils import set_form_field_order
from django import forms
from django.contrib.auth.forms import UserCreationForm

from user.models import User


class LoginForm(LoginForm):
    password = forms.CharField(
        widget=forms.TextInput(
            attrs={
                'id': 'password', 'class': 'form-control', 'type': 'password',
                'name': 'password', 'required': True, 'placeholder': 'Пароль',
                'autocomplete': 'off'
            }
        )
    )
    remember = forms.CharField(
        required=False, widget=forms.TextInput(
            attrs={
                'id': 'is_remember', 'class': 'form-check-input',
                'type': 'checkbox', 'name': 'is_remember'
            }
        )
    )

    def __init__(self, *args, **kwargs):
        self.request = kwargs.pop('request', None)
        super(LoginForm, self).__init__(*args, **kwargs)
        login_widget = forms.TextInput(attrs={
            'name': 'login', 'class': 'form-control', 'type': 'email',
            'placeholder': 'E-mail', 'required': True,
            'autofocus': 'autofocus', 'autocomplete': 'off',
            'onkeyup': 'this.value = this.value.toLowerCase();'
        })
        login_field = forms.EmailField(label="E-mail",
                                       widget=login_widget)

        self.fields["login"] = login_field
        set_form_field_order(self, ["login", "password", "remember"])
        if app_settings.SESSION_REMEMBER is not None:
            del self.fields['remember']


def login(self, *args, **kwargs):
    return super(LoginForm, self).login(*args, **kwargs)


class SignupForm(UserCreationForm):
    email = forms.CharField(
        widget=forms.TextInput(
            attrs={
                'id': 'email', 'class': 'form-control', 'type': 'email',
                'name': 'email', 'required': True, 'autocomplete': 'off',
                'placeholder': 'Адрес электронной почты',
                'onkeyup': 'this.value = this.value.toLowerCase();'
            }
        )
    )
    first_name = forms.CharField(
        widget=forms.TextInput(
            attrs={
                'id': 'first_name', 'class': 'form-control', 'type': 'text',
                'name': 'first_name', 'required': True, 'placeholder': 'Имя',
                'autocomplete': 'off', 'pattern': '^[A-Za-zА-Яа-я]+$'

            }
        )
    )
    last_name = forms.CharField(
        widget=forms.TextInput(
            attrs={
                'id': 'last_name', 'class': 'form-control', 'type': 'text',
                'name': 'last_name', 'required': True, 'placeholder': 'Фамилия',
                'autocomplete': 'off', 'pattern': '^[A-Za-zА-Яа-я]+$'
            }
        )
    )
    birthday = forms.CharField(
        widget=forms.TextInput(
            attrs={
                'id': 'birthday', 'class': 'form-control', 'type': 'date',
                'name': 'birthday', 'required': True,
                'autocomplete': 'off'
            }
        )
    )
    password1 = forms.CharField(
        widget=forms.PasswordInput(
            attrs={
                'id': 'password1', 'class': 'form-control', 'type': 'password',
                'name': 'password1', 'required': True, 'placeholder': 'Пароль',
                'autocomplete': 'off', 'min_length': 8
            }
        )
    )
    password2 = forms.CharField(
        widget=forms.PasswordInput(
            attrs={
                'id': 'password2', 'class': 'form-control', 'type': 'password',
                'name': 'password2', 'required': True, 'min_length': 8,
                'placeholder': 'Повторите пароль', 'autocomplete': 'off'
            }
        )
    )

    class Meta:
        model = User
        fields = (
            'email', 'first_name', 'last_name', 'birthday', 'password1',
            'password2'
        )


class UserImageForm(forms.ModelForm):
    x = forms.FloatField(widget=forms.HiddenInput())
    y = forms.FloatField(widget=forms.HiddenInput())
    width = forms.FloatField(widget=forms.HiddenInput())
    height = forms.FloatField(widget=forms.HiddenInput())

    class Meta:
        model = User
        fields = ('image', 'x', 'y', 'width', 'height')
        widgets = {
            'image': forms.FileInput(attrs={
                'accept': 'image/*', 'class': 'custom-file-input',
                'type': 'file'
            })
        }

    def save(self):
        user_image = super(UserImageForm, self).save()
        x = self.cleaned_data.get('x')
        y = self.cleaned_data.get('y')
        w = self.cleaned_data.get('width')
        h = self.cleaned_data.get('height')
        image = Image.open(user_image.image)
        cropped_image = image.crop((x, y, w + x, h + y))
        resized_image = cropped_image.resize((300, 300), Image.ANTIALIAS)
        resized_image.save(user_image.image.path)
        return user_image

user/views.py
from django.shortcuts import redirect, get_object_or_404
from django.views.generic import DetailView
from django.views.generic.base import View

from user.forms import UserImageForm
from user.models import User
from chat.models import Message


class UserDetailView(DetailView):
    def get_object(self):
        return get_object_or_404(User, id=self.request.user.id)

    def get_context_data(self, **kwargs):
        unread_counter = Message.objects.filter(
            chat__user_list=self.request.user, is_read=False
        ).exclude(author=self.request.user).count()
        context = {'userPage': True, 'unread_counter': unread_counter}
        return context


class UpdateImage(View):
    def post(self, request):
        form = UserImageForm(request.POST, request.FILES, instance=request.user)
        if form.is_valid():
            form.save()
            return redirect('my_profile')

templates/user/user_detail.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
    {{ request.user.first_name }} {{ request.user.last_name }}
{% endblock title %}


{% block unread_counter %}
    {% if unread_counter %}
        <span class="badge badge-primary badge-pill">{{ unread_counter }}</span>
    {% endif %}
{% endblock unread_counter %}

{% block content %}
    <div class="page-header header-filter" data-parallax="true"></div>

    <div class="main main-raised">
        <div class="profile-content">
            <div class="container">
                <div class="row">
                    <div class="col-md-3 ml-auto mr-auto">
                        <div class="profile">
                            <div class="avatar">
                                <img src="{{ request.user.image.url }}" id="profileImage"
                                     class="border rounded-circle border-primary">
                                <form action="{% url 'update_image' %}" class="hover-container" method="post"
                                      enctype="multipart/form-data" id="formUpload">
                                    <div class="middle rounded-circle justify-content-center">
                                        {% csrf_token %}
                                        {% if  request.user.image == 'default.png' %}
                                            <i class="material-icons">add_a_photo</i>
                                        {% else %}
                                            <i class="material-icons">edit</i>
                                        {% endif %}
                                        <input type="file" name="image" accept="image/*" class="custom-file-input" required="" id="id_image">
                                        <input type="hidden" name="x" id="id_x">
                                        <input type="hidden" name="y" id="id_y">
                                        <input type="hidden" name="width" id="id_width">
                                        <input type="hidden" name="height" id="id_height">
                                    </div>
                                </form>

                                <div class="modal fade" id="modalCrop" role="dialog" aria-labelledby="modalCropLabel"
                                     aria-hidden="true">
                                    <div class="modal-dialog" role="document">
                                        <div class="modal-content">
                                            <div class="modal-header">
                                                <h5 class="modal-title" id="modalCropLabel">Редактирование
                                                    изображения</h5>
                                                <button type="button" class="close" data-dismiss="modal"
                                                        aria-label="Close">
                                                    <span aria-hidden="true">&times;</span>
                                                </button>
                                            </div>

                                            <div class="modal-body">
                                                <img src="" id="image" style="max-width: 100%;">
                                            </div>

                                            <div class="modal-footer">
                                                <div class="btn-group pull-left" role="group">
                                                    <button type="button" class="btn js-zoom-in">
                                                        <i class="material-icons">zoom_in</i>
                                                    </button>

                                                    <button type="button" class="btn js-zoom-out">
                                                        <i class="material-icons">zoom_out</i>
                                                    </button>
                                                </div>
                                                <button type="button" class="btn btn-primary js-crop-and-upload">
                                                    Сохранить
                                                </button>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>

                            <div class="name">
                                <h3 class="title">
                                    {{ request.user.first_name }} {{ request.user.last_name }}
                                    {% if request.user.is_staff %}
                                        <i class="material-icons verified">verified_user</i>
                                    {% endif %}
                                </h3>
                                {% if request.user.is_staff %}
                                    <h6>Admin</h6>
                                {% endif %}
                            </div>
                        </div>
                    </div>
                </div>

                <div class="description text-center">
                    <p>Может быть здесь будет ваш статус :)</p>
                </div>

                <div class="row">
                    <div class="col-md-6 ml-auto mr-auto">
                        <div class="profile-tabs">
                            <ul class="nav nav-pills nav-pills-icons justify-content-center" role="tablist">
                                <li class="nav-item">
                                    <a class="nav-link active" href="#images" role="tab" data-toggle="tab">
                                        <i class="material-icons">photo_library</i>
                                        Фото
                                    </a>
                                </li>

                                <li class="nav-item">
                                    <a class="nav-link" href="#videos" role="tab" data-toggle="tab">
                                        <i class="material-icons">video_library</i>
                                        Видео
                                    </a>
                                </li>

                                <li class="nav-item">
                                    <a class="nav-link" href="#music" role="tab" data-toggle="tab">
                                        <i class="material-icons">library_music</i>
                                        Музыка
                                    </a>
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>

                <div class="tab-content tab-space">
                    <div class="tab-pane active text-center gallery" id="images">
                        <button class="btn btn-link">
                            <i class="fa fa-plus"></i>
                        </button>
                        <div class="row">
                            <div class="col-md-6 ml-auto">
                                <img src="//images.unsplash.com/photo-1524498250077-390f9e378fc0?ixlib=rb-0.3.5&ixid=eyJhcHBfaWQiOjEyMDd9&s=83079913579babb9d2c94a5941b2e69d&auto=format&fit=crop&w=751&q=80"
                                     class="rounded">
                                <img src="//images.unsplash.com/photo-1528249227670-9ba48616014f?ixlib=rb-0.3.5&ixid=eyJhcHBfaWQiOjEyMDd9&s=66b8e7db17b83084f16fdeadfc93b95b&auto=format&fit=crop&w=357&q=80"
                                     class="rounded">
                            </div>

                            <div class="col-md-6 mr-auto">
                                <img src="//images.unsplash.com/photo-1521341057461-6eb5f40b07ab?ixlib=rb-0.3.5&ixid=eyJhcHBfaWQiOjEyMDd9&s=72da2f550f8cbd0ec252ad6fb89c96b2&auto=format&fit=crop&w=334&q=80"
                                     class="rounded">
                                <img src="//images.unsplash.com/photo-1506667527953-22eca67dd919?ixlib=rb-0.3.5&ixid=eyJhcHBfaWQiOjEyMDd9&s=6326214b7ce18d74dde5e88db4a12dd5&auto=format&fit=crop&w=750&q=80"
                                     class="rounded">
                            </div>
                        </div>
                    </div>

                    <div class="tab-pane text-center gallery" id="videos">
                        <button class="btn btn-link">
                            <i class="fa fa-plus"></i>
                        </button>
                        <div class="row">
                            <div class="col-md-12 ml-auto">
                                <img src="//images.unsplash.com/photo-1524498250077-390f9e378fc0?ixlib=rb-0.3.5&ixid=eyJhcHBfaWQiOjEyMDd9&s=83079913579babb9d2c94a5941b2e69d&auto=format&fit=crop&w=751&q=80"
                                     class="rounded">
                                <img src="//images.unsplash.com/photo-1506667527953-22eca67dd919?ixlib=rb-0.3.5&ixid=eyJhcHBfaWQiOjEyMDd9&s=6326214b7ce18d74dde5e88db4a12dd5&auto=format&fit=crop&w=750&q=80"
                                     class="rounded">
                                <img src="//images.unsplash.com/photo-1505784045224-1247b2b29cf3?ixlib=rb-0.3.5&ixid=eyJhcHBfaWQiOjEyMDd9&s=ec2bdc92a9687b6af5089b335691830e&auto=format&fit=crop&w=750&q=80"
                                     class="rounded">
                            </div>

                            <div class="col-md-12 mr-auto">
                                <img src="//images.unsplash.com/photo-1504346466600-714572c4b726?ixlib=rb-0.3.5&ixid=eyJhcHBfaWQiOjEyMDd9&s=6754ded479383b7e3144de310fa88277&auto=format&fit=crop&w=750&q=80"
                                     class="rounded">
                                <img src="//images.unsplash.com/photo-1494028698538-2cd52a400b17?ixlib=rb-0.3.5&ixid=eyJhcHBfaWQiOjEyMDd9&s=83bf0e71786922a80c420c17b664a1f5&auto=format&fit=crop&w=334&q=80"
                                     class="rounded">
                            </div>
                        </div>
                    </div>

                    <div class="tab-pane text-center gallery" id="music">
                        <button class="btn btn-link">
                            <i class="fa fa-plus"></i>
                        </button>
                        <div class="row">
                            <div class="col-md-3 ml-auto">
                                <img src="//images.unsplash.com/photo-1504346466600-714572c4b726?ixlib=rb-0.3.5&ixid=eyJhcHBfaWQiOjEyMDd9&s=6754ded479383b7e3144de310fa88277&auto=format&fit=crop&w=750&q=80"
                                     class="rounded">
                                <img src="//images.unsplash.com/photo-1494028698538-2cd52a400b17?ixlib=rb-0.3.5&ixid=eyJhcHBfaWQiOjEyMDd9&s=83bf0e71786922a80c420c17b664a1f5&auto=format&fit=crop&w=334&q=80"
                                     class="rounded">
                            </div>

                            <div class="col-md-3 mr-auto">
                                <img src="//images.unsplash.com/photo-1505784045224-1247b2b29cf3?ixlib=rb-0.3.5&ixid=eyJhcHBfaWQiOjEyMDd9&s=ec2bdc92a9687b6af5089b335691830e&auto=format&fit=crop&w=750&q=80"
                                     class="rounded">
                                <img src="//images.unsplash.com/photo-1524498250077-390f9e378fc0?ixlib=rb-0.3.5&ixid=eyJhcHBfaWQiOjEyMDd9&s=83079913579babb9d2c94a5941b2e69d&auto=format&fit=crop&w=751&q=80"
                                     class="rounded">
                                <img src="//images.unsplash.com/photo-1506667527953-22eca67dd919?ixlib=rb-0.3.5&ixid=eyJhcHBfaWQiOjEyMDd9&s=6326214b7ce18d74dde5e88db4a12dd5&auto=format&fit=crop&w=750&q=80"
                                     class="rounded">
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}

{% block javascript %}
    <script src="{% static 'js/crop.js' %}" type="text/javascript"></script>
{% endblock javascript %}